name: smartszyme_dev2
channels:
  - anaconda
  - conda-forge
  - defaults
dependencies:
  - matplotlib=3.8.4
  - mdtraj=1.9.9
  - numpy=1.26.4
  - pandas=2.2.0
  - pip=23.3.1
  - python=3.10.13
  - scikit-learn=1.3.0
  - scipy=1.12.0
  - numexpr=2.8.4
  - pyarrow=14.0.2